/// Audio + haptics gate — spec §23 / PH-04.
///
/// `assets/audio/` ships 8 SFX + `bgm.mp3`, generated by `tool/generate_audio.py`.
/// [init] preloads them; on a host without the audio plugin (every `flutter test`
/// run) the preload throws, `_ready` stays false, and [play] / [haptic] are inert.
/// Settings toggles drive [setSoundEnabled] and [setHapticsEnabled].
library;

import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/services.dart';

import 'save_store.dart';

/// The eight documented cue names from spec §23, plus [bgm]. Kept as constants
/// so call sites never invent a filename the preload list does not know about.
abstract final class Sfx {
  static const place = 'place.mp3';
  static const collect = 'collect.mp3';
  static const shoot = 'shoot.mp3';
  static const hit = 'hit.mp3';
  static const explosion = 'explosion.mp3';
  static const win = 'win.mp3';
  static const lose = 'lose.mp3';
  static const sweep = 'sweep.mp3';
  static const bgm = 'bgm.mp3';

  static const all = <String>[
    place,
    collect,
    shoot,
    hit,
    explosion,
    win,
    lose,
    sweep,
    bgm,
  ];
}

abstract final class GameAudio {
  static bool _sound = true;
  static bool _haptics = true;
  static bool _ready = false;

  static bool get soundEnabled => _sound;
  static bool get hapticsEnabled => _haptics;

  /// Call once at boot after [SaveStore.open]. Preloads all 8 SFX cues + BGM
  /// from `assets/audio/`. In tests or missing-plugin hosts, falls back gracefully.
  static Future<void> init() async {
    _sound = SaveStore.I.state.sound;
    _haptics = SaveStore.I.state.haptics;
    try {
      await FlameAudio.audioCache.loadAll(Sfx.all);
      _ready = true;
    } catch (_) {
      // In headless test environments or missing asset bundle, stay silent.
      _ready = false;
    }
  }

  /// Settings Switch: volume 1 when on, 0 when off.
  ///
  /// Volume is applied to FlameAudio only after a successful [init] preload
  /// (`_ready`). In tests / missing-plugin hosts we only flip the gate flag.
  /// Note: does not call clearAll() (resolving AUD-018) to avoid clearing preloaded clips.
  static Future<void> setSoundEnabled(bool enabled) async {
    _sound = enabled;
    if (!_ready) return;
    try {
      // Master gate: callers check [_sound] before play; when ready, also
      // adjust the BGM bus so any ambient track respects the toggle.
      FlameAudio.bgm.audioPlayer.setVolume(enabled ? 1.0 : 0.0);
    } catch (_) {}
  }

  /// Start looping ambient background music if sound is enabled.
  static Future<void> startBgm() async {
    if (!_sound || !_ready) return;
    try {
      await FlameAudio.bgm.play(Sfx.bgm, volume: _sound ? 1.0 : 0.0);
    } catch (_) {}
  }

  /// Stop ambient background music.
  static Future<void> stopBgm() async {
    try {
      await FlameAudio.bgm.stop();
    } catch (_) {}
  }

  static void setHapticsEnabled(bool enabled) => _haptics = enabled;

  /// Play a one-shot. No-op when sound is off or assets are missing.
  static Future<void> play(String file) async {
    if (!_sound || !_ready) return;
    try {
      await FlameAudio.play(file);
    } catch (_) {
      // Missing asset or plugin host — stay silent.
    }
  }

  /// Light impact when haptics are on; no-op otherwise.
  static Future<void> haptic() async {
    if (!_haptics) return;
    try {
      await HapticFeedback.lightImpact();
    } catch (_) {}
  }

  /// Test seam: mark the bus as "ready" without loading files.
  static void debugSetReady(bool ready) => _ready = ready;
}
